apiVersion: v1
kind: Service
metadata:
  name: {{ include "station.giteaName" . }}
  labels:
    {{- include "station.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gitea.service.type }}
  ports:
    - name: http
      port: {{ .Values.gitea.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: ssh
      port: {{ .Values.gitea.service.sshPort }}
      targetPort: ssh
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "station.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gitea
