apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "station.initdbConfigName" . }}
  labels:
    {{- include "station.labels" . | nindent 4 }}
data:
  01-create-databases.sql: |-
{{ .Files.Get "initdb/01-create-databases.sql" | indent 4 }}
