apiVersion: v1
kind: Service
metadata:
  name: {{ include "station.postgresName" . }}
  labels:
    {{- include "station.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "station.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
