apiVersion: v1
kind: Service
metadata:
  name: {{ include "station.fullname" . }}
  labels:
    {{- include "station.labels" . | nindent 4 }}
spec:
  type: {{ .Values.station.service.type }}
  ports:
    - name: http
      port: {{ .Values.station.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.station.service.type "NodePort") .Values.station.service.nodePort }}
      nodePort: {{ .Values.station.service.nodePort }}
      {{- end }}
  selector:
    {{- include "station.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: station
