{{- $confFiles := .Files.Glob "station-config/default-configs/conf/**" }}
{{- $connectorFiles := .Files.Glob "station-config/default-configs/connectors/**" }}
{{- $topologyFiles := .Files.Glob "station-config/default-configs/topology/**" }}
{{- $modelFiles := .Files.Glob "station-config/default-configs/models/**" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "station.defaultConfigsName" . }}
  labels:
    {{- include "station.labels" . | nindent 4 }}
data:
{{- range $path, $_ := $confFiles }}
  {{ trimPrefix "station-config/default-configs/" $path | replace "/" "__" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- range $path, $_ := $connectorFiles }}
  {{ trimPrefix "station-config/default-configs/" $path | replace "/" "__" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- range $path, $_ := $topologyFiles }}
  {{ trimPrefix "station-config/default-configs/" $path | replace "/" "__" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- range $path, $_ := $modelFiles }}
  {{ trimPrefix "station-config/default-configs/" $path | replace "/" "__" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
