apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "station.stationConfigName" . }}
  labels:
    {{- include "station.labels" . | nindent 4 }}
data:
  config.toml: |-
{{ .Files.Get "station-config/config.toml" | indent 4 }}
