replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

station:
  image:
    repository: ghcr.io/wp-labs/wp-station
    pullPolicy: IfNotPresent
    tag: "v0.1.11-alpha"
  toolchainImage:
    repository: ghcr.io/wp-labs/warp-parse
    pullPolicy: IfNotPresent
    tag: "0.23.8-alpha"
  initImage:
    repository: busybox
    pullPolicy: IfNotPresent
    tag: "1.36"
  web:
    host: 0.0.0.0
    port: 8081
  log:
    level: debug
  git:
    userName: WarpStation
    userEmail: station@warpparse.local
  configMountPath: /app/config/config.toml
  defaultConfigsMountPath: /app/default_configs
  toolchainMountPath: /app/toolchain
  monitorUrl: http://wp-monitor:18080/wp-monitor
  assistBaseUrl: ""
  projectRoot: project_root
  service:
    type: ClusterIP
    port: 8081
    nodePort: null
  env: []
  envFrom: []
  timezone:
    enabled: true
    name: Asia/Shanghai
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

postgres:
  image:
    repository: postgres
    tag: "18.3"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  user: postgres
  password: "123456"
  databases:
    default: postgres
    gitea: gitea
    station: wp-station
  persistence:
    enabled: true
    storageClassName: ""
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

gitea:
  image:
    repository: gitea/gitea
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    httpPort: 3000
    sshPort: 22
  adminUsername: gitea
  adminPassword: "123456"
  rootUrl: http://localhost:3000
  domain: localhost
  sshDomain: localhost
  sshExternalPort: 222
  userUid: "1000"
  userGid: "1000"
  persistence:
    enabled: true
    storageClassName: ""
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
