[sink_group]
name = "all"
oml = ["*"]

# vlog
[[sink_group.sinks]]
name = "victorialogs_output"
connect = "victorialogs_sink"
[sink_group.sinks.params]
endpoint = "http://wp-monitor-victoria-logs:9428"
api_path = "/insert/jsonline?_msg_field=content,log"

# [[sink_group.sinks]]
# name = "all_sink"
# connect = "file_json_sink"
# tags = []

# [sink_group.sinks.params]
# base = "./data/out_dat/"
# file = "all2.json"
