replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

wparse:
  image:
    repository: ghcr.io/wp-labs/warp-parse
    pullPolicy: IfNotPresent
    tag: "0.23.8-alpha"
  initImage:
    repository: busybox
    pullPolicy: IfNotPresent
    tag: "1.36"
  workDir: /app/config
  warpParseSecretPath: /root/.warp_parse
  command:
    - wparse
  args:
    - deamon
    - --work-root
    - /app/config
  # env:
  #   - name: GIT_REPO
  #     value: http://wp-station-gitea:3000
  #   - name: VICTORIA_METRICS_ENDPOINT
  #     value: http://wp-monitor-victoria-metrics:8428
  envFrom: []
  timezone:
    enabled: true
    name: Asia/Shanghai
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  warpParseSecret:
    existingSecret: ""
  service:
    type: ClusterIP
    primaryPort: 19002
    ports:
      - name: tcp
        port: 19002
        containerPort: 19002
        targetPort: tcp
        protocol: TCP
        nodePort: null
  adminService:
    type: ClusterIP
    port: 19090
    nodePort: null
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  httpRoute:
    enabled: false
    annotations: {}
    parentRefs:
      - name: gateway
        sectionName: http
    hostnames:
      - chart-example.local
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
