{{- if and (not .Values.wparse.warpParseSecret.existingSecret) (include "wparse.hasBundledWarpParseToken" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wparse.warpParseSecretName" . }}
  labels:
    {{- include "wparse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $token := .Files.Get ".warp_parse/admin_api.token" }}
  admin_api.token: |-
{{ $token | indent 4 }}
  {{- if include "wparse.hasBundledWarpParseTls" . }}
  {{- $crt := .Files.Get ".warp_parse/tls/server.crt" }}
  {{- $key := .Files.Get ".warp_parse/tls/server.key" }}
  tls.crt: |-
{{ $crt | indent 4 }}
  tls.key: |-
{{ $key | indent 4 }}
  {{- end }}
{{- end }}
